# SPDX-License-Identifier: GPL-2.0
#
# This file should be included by external modules that need to link to this
# project.

EXTRA_CFLAGS += -I$(KERNEL_SRC)/../gs/google-modules/raviole-device/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../gs/google-modules/raviole-device/include/uapi

EXTRA_SYMBOLS += $(OUT_DIR)/../gs/google-modules/raviole-device/Module.symvers
