# SPDX-License-Identifier: GPL-2.0

LINUXINCLUDE += \
		-I$(srctree)/$(KBUILD_EXT_TREE)/include \
		-I$(srctree)/$(KBUILD_EXT_TREE)/include/uapi \
		-I$(srctree)/$(KBUILD_EXT_TREE)/arch/$(SRCARCH)/include/uapi

dtstree := $(KBUILD_EXT_TREE)/arch/$(SRCARCH)/boot/dts

